=== TonyUrena/DAM/MARCAS/04/Tarea03/examen/Ejer03/Ejer03.dtd
<!ELEMENT email (de, para, contenido)>
<!ATTLIST email fecha CDATA #REQUIRED>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT contenido (saludo, ejercicios, despedida)>
<!ELEMENT saludo (#PCDATA | persona)*>
<!ELEMENT persona (#PCDATA)>
<!ELEMENT ejercicios (ejercicio+)>
<!ELEMENT ejercicio (tema, descripcion)>
<!ATTLIST ejercicio codigo ID #REQUIRED>
<!ATTLIST ejercicio resuelto (si | no) #IMPLIED>
<!ELEMENT tema (#PCDATA)>
<!ATTLIST tema importancia (baja | alta) #IMPLIED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT despedida (#PCDATA)>

=== TonyUrena/DAM/MARCAS/04/Tarea03/examen/Ejer03/Ejer03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email SYSTEM "Ejer03.dtd">
<email fecha="07-02-2023">
    <de> luca.917@gmail.com </de>
    <para> atzen@uniroma.com </para>
    <contenido>
        <saludo> Hola <persona> Ramon </persona> ,te mando los ejercicios. </saludo>
        <ejercicios>
            <ejercicio codigo="A001" resuelto= "si">
                <tema importancia= "baja"> DTD </tema>
                <descripcion> convertir ficheros XML </descripcion>
            </ejercicio>
            <ejercicio codigo= "A002">
                <tema> XSD </tema>
                <descripcion> definir esquemas </descripcion>
            </ejercicio>
        </ejercicios>
        <despedida> Hasta otra </despedida>
    </contenido>
</email>
