=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio05.dtd
<!ELEMENT deviceid (model, fwversion, serial, cueid,
                    language+)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT fwversion (#PCDATA)>
<!ELEMENT serial (#PCDATA)>
<!ELEMENT cueid (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio05.xml
<!DOCTYPE deviceid SYSTEM "./Ejercicio05.dtd">
<deviceid>
    <model>320</model>
    <fwversion>V0.640</fwversion>
    <serial>CN125678FB</serial>
    <cueid>#Hewlett-Packard#Cam320#CN125678FB</cueid>
    <language>en</language>
    <language>es</language>
    <language>it</language>
</deviceid>
