=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio03.dtd
<!ELEMENT libros (primerLibro, segundoLibro, tercerLibro,
                cuartoLibro, quintoLibro)>

<!ELEMENT primerLibro (titulo, autor, ISBN, precio)>
<!ELEMENT segundoLibro (titulo, autor+, ISBN, precio)>
<!ELEMENT tercerLibro (titulo, autor, precio)>
<!ELEMENT cuartoLibro (titulo, autor, ISBN, precio+)>
<!ELEMENT quintoLibro (titulo, autor, ISBN)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio03.xml
<!DOCTYPE libros SYSTEM "./Ejercicio03.dtd">
<libros>
    <primerLibro>
        <titulo>AAA</titulo>
        <autor>AAAA</autor>
        <ISBN>AAA</ISBN>
        <precio>111</precio>
    </primerLibro>
    <segundoLibro>
        <titulo>AAA</titulo>
        <autor>AAAA</autor>
        <autor>AAAA</autor>
        <ISBN>AAA</ISBN>
        <precio>111</precio>
    </segundoLibro>
    <tercerLibro>
        <titulo>AAA</titulo>
        <autor>AAAA</autor>
        <precio>123</precio>
    </tercerLibro>
    <cuartoLibro>
        <titulo>AAA</titulo>
        <autor>AAAA</autor>
        <ISBN>AAA</ISBN>
        <precio>123</precio>
        <precio>123</precio>
    </cuartoLibro>
    <quintoLibro>
        <titulo>AAA</titulo>
        <autor>AAAA</autor>
        <ISBN>AAA</ISBN>
    </quintoLibro>
</libros>
