=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio01.dtd
<!ELEMENT biblioteca (socio+)>
<!ELEMENT socio (nombre, apellidos)>
<!ATTLIST socio DNI CDATA #REQUIRED
                numeroSocio CDATA #REQUIRED 
                descuento (si | no) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio01.xml
<!DOCTYPE biblioteca SYSTEM "./Ejercicio01.dtd">
<biblioteca>
    <socio DNI="12345678W" numeroSocio="123" descuento="no">
        <nombre>PACO</nombre>
        <apellidos>Of Lucy</apellidos>
    </socio>
    <socio DNI="12345678W" numeroSocio="123" descuento="no">
        <nombre>PACO</nombre>
        <apellidos>Of Lucy</apellidos>
    </socio>
    <socio DNI="12345678W" numeroSocio="123" descuento="no">
        <nombre>PACO</nombre>
        <apellidos>Of Lucy</apellidos>
    </socio>
    <socio DNI="12345678W" numeroSocio="123" descuento="no">
        <nombre>PACO</nombre>
        <apellidos>Of Lucy</apellidos>
    </socio>
</biblioteca>
