=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio06.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, apellidos, fechaNacimiento?, direccion+, (varon | mujer | otro))>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechaNacimiento EMPTY>
<!ATTLIST fechaNacimiento
    dia CDATA #REQUIRED
    mes CDATA #REQUIRED
    anyo CDATA #REQUIRED>

<!ELEMENT direccion (calle,poblacion,provincia,codigoPostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT codigoPostal (#PCDATA)>

<!ELEMENT varon EMPTY>
<!ELEMENT mujer EMPTY>
<!ELEMENT otro EMPTY>

=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio06.xml
<!DOCTYPE personas SYSTEM "Ejercicio06.dtd">
<personas>
    <persona>
        <nombre>AAAA</nombre>
        <apellidos>PaAAAArdo</apellidos>
        <fechaNacimiento dia="22" mes="NOviembre"
            anyo="1999" />
        <direccion>
            <calle>AAAAAA</calle>
            <poblacion>AAAAAA</poblacion>
            <provincia>AAAAA</provincia>
            <codigoPostal>12222</codigoPostal>
        </direccion>
        <varon />
    </persona>
    <persona>
        <nombre>AAAAAA</nombre>
        <apellidos>AAAAA</apellidos>
        <direccion>
            <calle>AAAAAAA</calle>
            <poblacion>AAAAAAA</poblacion>
            <provincia>AAAAA</provincia>
            <codigoPostal>12222</codigoPostal>
        </direccion>
        <direccion>
            <calle>AAAAAA</calle>
            <poblacion>AAAAA</poblacion>
            <provincia>AAAAAA</provincia>
            <codigoPostal>122222</codigoPostal>
        </direccion>
        <mujer />
    </persona>
    <persona>
        <nombre>AAAAAA</nombre>
        <apellidos>AAAAA</apellidos>
        <direccion>
            <calle>AAAAAAA</calle>
            <poblacion>AAAAAAA</poblacion>
            <provincia>AAAAA</provincia>
            <codigoPostal>12222</codigoPostal>
        </direccion>
        <direccion>
            <calle>AAAAAA</calle>
            <poblacion>AAAAA</poblacion>
            <provincia>AAAAAA</provincia>
            <codigoPostal>122222</codigoPostal>
        </direccion>
        <otro />
    </persona>
</personas>
