=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio02.dtd
<!ELEMENT universidad (alumno | profesor | asignatura)+>
<!ELEMENT alumno (((DNI | (pasaporte, pais)),
            ((nombre, apellido) | apellidos)),
            fechaNacimiento, asignaturaAlum*)>

<!ELEMENT profesor (((DNI | (pasaporte, pais)),
            ((nombre, apellido) | apellidos)),
            fechaNacimiento,
            despacho,
            horarioTutoria, asignaturaProf*)>

<!ELEMENT asignatura (nombre, creditos, carrera, curso)>
<!ATTLIST asignatura id ID #REQUIRED>

<!ELEMENT asignaturaAlum (nota)>
<!ATTLIST asignaturaAlum cod IDREF #REQUIRED>

<!ELEMENT asignaturaProf (#PCDATA)>
<!ATTLIST asignaturaProf cod IDREF #REQUIRED>

<!ELEMENT DNI (#PCDATA)>
<!ELEMENT pasaporte (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT despacho (#PCDATA)>
<!ELEMENT horarioTutoria (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

=== TonyUrena/DAM/MARCAS/04/Tarea02/Ejercicio02.xml
<!DOCTYPE universidad SYSTEM "./Ejercicio02.dtd">
<universidad>
    <asignatura id="AA">
        <nombre>AA</nombre>
        <creditos>30</creditos>
        <carrera>aaaaa</carrera>
        <curso>2</curso>
    </asignatura>
    <alumno>
        <DNI>12345678W</DNI>
        <nombre>aaaaaaa</nombre>
        <apellido>aaa aaaa</apellido>
        <fechaNacimiento>123</fechaNacimiento>
        <asignaturaAlum cod="AA">
            <nota>3</nota>
        </asignaturaAlum>
    </alumno>
    <profesor>
        <DNI>12345678W</DNI>
        <nombre>aaaaaaa</nombre>
        <apellido>aaa aaaa</apellido>
        <fechaNacimiento>123</fechaNacimiento>
        <despacho>aaa</despacho>
        <horarioTutoria>123</horarioTutoria>
        <asignaturaProf cod="AA"></asignaturaProf>
    </profesor>
</universidad>
