=== TonyUrena/DAM/MARCAS/04/Tarea03/examen/Ejer01/Ejer01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listacomponentes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="componente" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element ref="tarjetagrafica" />
                            <xs:element ref="monitor" />
                        </xs:choice>
                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:totalDigits value="6"></xs:totalDigits>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Declaracion
    Elementos-->

    <xs:element name="tarjetagrafica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="memoria" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]GB|[0-9]TB"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="precio" minOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="moneda" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="euros"></xs:enumeration>
                                            <xs:enumeration value="dolares"></xs:enumeration>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="monitor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tamanio">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:maxInclusive value="75"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="precio">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:float">
                                <xs:attribute name="moneda" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== TonyUrena/DAM/MARCAS/04/Tarea03/examen/Ejer01/Ejer01.xml
<?xml version="1.0" encoding="UTF-8"?>
<listacomponentes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejer01.xsd">
    <componente>
        <tarjetagrafica>
            <memoria>2GB</memoria>
            <precio moneda="euros">190</precio>
        </tarjetagrafica>
    </componente>
    <componente codigo="123456">
        <monitor>
            <tamanio>14</tamanio>
            <precio moneda="euros">99.49</precio>
        </monitor>
    </componente>
</listacomponentes>
